### ISSUE TITLE
Create an alias or particular struct for float  

### ISSUE THREAD

**Issue by HoshinoTented** [Inokinoki/softfpu-rs#3]
It should be useful.
And makes more crap.

**Comment by Inokinoki** [comment]
Like this?
https://github.com/Inokinoki/softfpu-rs/blob/dcb6a6c97bd6030a5a20374ee05d0645fa8fbdd0/src/soft_f32/mod.rs#L35

**Comment by HoshinoTented** [comment]
Yes, but I found that you didn't use it in some functions (like soft_f32_mul.rs).
Is it not complete yet?

**Comment by HoshinoTented** [comment]
:( sorry

**Comment by HoshinoTented** [comment]
so, is soft_f32_xxx.rs a low level operation implementation?

**Comment by Inokinoki** [comment]
Yes. There are low level impls in `soft_f32_xxx.rs`

and a struct with some traits in `mod.rs`, such as:

https://github.com/Inokinoki/softfpu-rs/blob/dcb6a6c97bd6030a5a20374ee05d0645fa8fbdd0/src/soft_f32/mod.rs#L79

**Comment by HoshinoTented** [comment]
got it

**Comment by Inokinoki** [comment]
Closed

**Comment by HoshinoTented** [comment]
Ummmm, but which I want:

```rust
struct HighLevelF32 {
    sign: Sign,    // u8 or bool?
    exp: u32,
    frac: u32
}
```

then, we can convert an `F32` to `HighLevelF32`:

```rust
let f: F32 = magic!();
let hf: HighLevelF32 = HighLevelF32::from(f);
```

**Comment by HoshinoTented** [comment]
because there are many duplicated code like:

```rust
let mut a_sign = something;
let mut b_sign = something;
```

if we have a `HighLevelF32`, we can:

```rust
let mut HighLevelF32 {
    a_sign,
    a_exp,
    a_frac
} = something_was_high_level_f32;
```

**Comment by Inokinoki** [comment]
> because there are many duplicated code like:
> 
> ```rust
> let mut a_sign = something;
> let mut b_sign = something;
> ```
> 
> if we have a `HighLevelF32`, we can:
> 
> ```rust
> let mut HighLevelF32 {
>     a_sign,
>     a_exp,
>     a_frac
> } = something_was_high_level_f32;
> ```

In fact, the project is just an intermedia project. Finally, my target was to implement [SoftFPU in ASL for ACPI](https://github.com/Inokinoki/acpi-softfpu). Therefore the core things are much more C-style without many Rust features.

I prefer to maintain low-level impl as simple as possible and expose some high-level interfaces, such as F32 to Rust users.

**Comment by HoshinoTented** [comment]
ok
